var quotes = [
  {quote: "Whatever house I'm in, I hope she's not in it.",
    source: "Ron Weasley",
    citation: "Harry Potter and the Sorceror's Stone",
    year: 1997,
    tag: "Funny"
  },
  {quote: "I hope you are pleased with yourselves. We could have been killed - or worse, expelled.",
    source: "Hermione Granger",
    citation: "Harry Potter and the Sorceror's Stone",
    year: "1997",
    tag: "Funny"
  },
  {quote: "Ah, yes. Harry Potter. Our new - celebrity.",
    source: "Snape",
    citation: "Harry Potter and the Sorceror's Stone",
    year: 1997,
    tag: "Hate"
  },
  {quote: "It does not do to dwell on dreams and forget to live, remember that.",
    source: "Albus Dumbledore",
    citation: "Harry Potter and the Sorceror's Stone",
    year: 1992,
    tag: "Inspiration"
  },
  {quote: "It is our choices, Harry, that show what we truly are, far more than our abilities.",
    source: "Albus Dumbledore",
    citation: "Harry Potter and the Chamber of Secrets",
    year: 1993,
    tag: "Inspiration"
  },
  {quote: "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.",
    source: "Albus Dumbledore",
    citation: "Harry Potter and the Prisoner of Azkaban",
    year: 1994,
    tag: "Inspiration"
  },
  {quote: "Differences of habit and language are nothing at all if our aims are identical and our hearts are open.",
    source: "Albus Dumbledore",
    citation: "Harry Potter and the Goblet of Fire",
    year: 1995,
    tag: "Love"
  },
  {quote: "Youth cannot know how age thinks and feels. But old men are guilty if they forget what it was to be young...",
    source: "Albus Dumbledore",
    citation: "Harry Potter and the Order of the Phoenix",
    year: 1996,
    tag: "Age"
  },
  {quote: "Age is foolish and forgetful when it underestimates youth.",
    source: "Albus Dumbledore",
    citation: "Harry Potter and the Half-Blood Prince",
    year: 1997,
    tag: "Age"
  },
  {quote: "It is the unknown we fear when we look upon death and darkness, nothing more.",
    source: "Albus Dumbledore",
    citation: "Harry Potter and the Half-Blood Prince",
    year: 1997,
    tag: "Inspiration"
  },
  {quote: "Scars can come in useful. I have one myself above my left knee which is a perfect map of the London Underground.",
    source: "Albus Dumbledore",
    citation: "Harry Potter and the Sorceror's Stone",
    year: 1997,
    tag: "Funny"
  },
  {quote: "Of all the trees we could've hit, we had to get one that hits back.",
    source: "Ron Weasley",
    citation: "Harry Potter and the Chamber of Secrets",
    year: 1998,
    tag: "Funny"
  },
  {quote: "I must ask you not to scream, ...It might provoke them... Yes, freshly caught Cornish pixies.",
    source: "Gilderoy Lockhart",
    citation: "Harry Potter and the Chamber of Secrets",
    year: 1998,
    tag: "Funny"
  },
  {quote: "No one asked your opinion, you filthy Mudblood.",
    source: "Draco Malfoy",
    citation: "Harry Potter and the Chamber of Secrets",
    year: 1998,
    tag: "Hate"
  },
  {quote: "Hearing voices no one else can hear isn't a good sign, even in the wizarding world.",
    source: "Hermione Granger",
    citation: "Harry Potter and the Chamber of Secrets",
    year: 1998,
    tag: "Truth"
  },
  {quote: "At least no one on Gryffindor team had to buy their way in. They got in on pure talent.",
    source: "Hermione Granger",
    citation: "Harry Potter and the Chamber of Secrets",
    year: 1998,
    tag: "Truth"
  },
  {quote: "Lockhart'll sign anything if it stands still long enough.",
    source: "Ron Weasley",
    citation: "Harry Potter and the Chamber of Secrets",
    year: 1998,
    tag: "Truth"
  },
  {quote: "Never trust anything that can think for itself if you can't see where it keeps its brain.",
    source: "Arthur Weasley",
    citation: "Harry Potter and the Chamber of Secrets",
    year: 1998,
    tag: "Truth"
  },
  {quote: "I don't go looking for trouble. Trouble usually finds me.",
    source: "Harry Potter",
    citation: "Harry Potter and the Prisoner of Azkaban",
    year: 1999,
    tag: "Truth"
  },
  {quote: "We tried to shut Percy in a pyramid. But Mum spotted us.",
    source: "George Weasley",
    citation: "Harry Potter and the Prisoner of Azkaban",
    year: 1999,
    tag: "Funny"
  },
  {quote: "I'm not blamin' yeh... but I gotta tell yeh, I thought you two'd value yer friendship more'n broomsticks or rats. Tha's all.",
    source: "Hagrid",
    citation: "Harry Potter and the Prisoner of Azkaban",
    year: 1999,
    tag: "Truth"
  },
  {quote: "When a wizard goes over to the Dark Side there's nothin' and no one matters to 'em anymore...'",
    source: "Hagrid",
    citation: "Harry Potter and the Prisoner of Azkaban",
    year: 1999,
    tag: "Hate"
  },
  {quote: "If you made a better rat than a human Peter, that's not much to boast about.",
    source: "Sirius Black",
    citation: "Harry Potter and the Prisoner of Azkaban",
    year: 1999,
    tag: "Funny"
  },
  {quote: "I assure you that if you die, you need not hand it [homework] in.",
    source: "McGonagall",
    citation: "Harry Potter and the Prisoner of Azkaban",
    year: 1999,
    tag: "Funny"
  },
  {quote: "Your parents gave their lives to keep you alive, Harry. A poor way to repay them - gambling their sacrafice for a bag of magic tricks.",
    source: "Lupin",
    citation: "Harry Potter and the Prisoner of Azkaban",
    year: 1999,
    tag: "Truth"
  },
  {quote: "If you want to kill Harry, you'll have to kill us, too.",
    source: "Ron Weasley",
    citation: "Harry Potter and the Prisoner of Azkaban",
    year: 1999,
    tag: "Love"
  },
  {quote: "CONSTANT VIGILANCE!",
    source: "Mad-Eye Moody",
    citation: "Harry Potter and the Goblet of Fire",
    year: 2000,
    tag: "Funny"
  },
  {quote: "Remember if the time should come when you have to make a choice between what is right and what is easy, remember what happened to a boy who was good, and kind, and brave, because he strayed across the path of Lord Voldemort. Remember Cedric Diggory.",
    source: "Dumbledore",
    citation: "Harry Potter and the Goblet of Fire",
    year: 2000,
    tag: "Inspiration"
  },
  {quote: "My own brother, Aberforth, was prosecuted for practicing inappropriate charms on a goat. It was all over the papers, but did Aberforth hide? No, he did not! He held his head high and went about his business as usual! Of course, I'm not entirely sure he can read, so that may not have been bravery...",
    source: "Dumbledore",
    citation: "Harry Potter and the Goblet of Fire",
    year: 2000,
    tag: "Funny"
  },
  {quote: "We are only as strong as we are united, as weak as we are divided.",
    source: "Dumbledore",
    citation: "Harry Potter and the Goblet of Fire",
    year: 2000,
    tag: "Inspiration"
  },
  {quote: "Curiousity is not a sin. But we should exercise caution with our curiosity.",
    source: "Dumbledore",
    citation: "Harry Potter and the Goblet of Fire",
    year: 2000,
    tag: "Truth"
  },
  {quote: "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.",
    source: "Sirius Black",
    citation: "Harry Potter and the Goblet of Fire",
    year: 2000,
    tag: "Truth"
  },
  {quote: "Kill the spare.",
    source: "Lord Voldemort",
    citation: "Harry Potter and the Goblet of Fire",
    year: 2000,
    tag: "Hate"
  },
  {quote: "What's coming will come, and we'll meet it when it does.",
    source: "Hagrid",
    citation: "Harry Potter and the Goblet of Fire",
    year: 2000,
    tag: "Inspiration"
  },
  {quote: "CONSTANT VIGILANCE!",
    source: "Mad-Eye Moody",
    citation: "Harry Potter and the Goblet of Fire",
    year: 2000,
    tag: "Funny"
  },
  {quote: "Indifference and neglect often do much more damage than outright dislike.",
    source: "Dumbledore",
    citation: "Harry Potter and the Order of the Phoenix",
    year: 2003,
    tag: "Hate"
  },
  {quote: "Wit beyond measure is a man's greatest treasure.",
    source: "Luna Lovegood",
    citation: "Harry Potter and the Order of the Phoenix",
    year: 2003,
    tag: "Truth"
  },
  {quote: "ARE YOU MAD, MAD-EYE?",
    source: "Nymphadora Tonks",
    citation: "Harry Potter and the Order of the Phoenix",
    year: 2003,
    tag: "Funny"
  },
  {quote: "Hermione, we've been through this before... We're not going through every exam afterward; it's bad enough doing them once.",
    source: "Ron Weasley",
    citation: "Harry Potter and the Order of the Phoenix",
    year: 2003,
    tag: "Truth"
  },
  {quote: "The Prophet is bound to report the truth occasionally, if only accidentally.",
    source: "Dumbledore",
    citation: "Harry Potter and the Half-Blood Prince",
    year: 2005,
    tag: "Funny"
  },
  {quote: "Dumbledore says people find it far easier to forgive others for being wrong than being right.",
    source: "Hermione Granger",
    citation: "Harry Potter and the Half-Blood Prince",
    year: 2005,
    tag: "Truth"
  },
  {quote: "I liked the DA, too. It was like having friends.",
    source: "Luna Lovegood",
    citation: "Harry Potter and the Half-Blood Prince",
    year: 2005,
    tag: "Truth"
  },
  {quote: "You dare use my own spells against me, Potter? It was I who invented them — I, the Half-Blood Prince! And you'd turn them on me like your filthy father, would you? I don't think so...No!",
    source: "Snape",
    citation: "Harry Potter and the Half-Blood Prince",
    year: 2005,
    tag: "Hate"
  },
  {quote: "Well, we find we appreciate you more and more, Mum, now we're washing our own socks.",
    source: "George Weasley",
    citation: "Harry Potter and the Half-Blood Prince",
    year: 2005,
    tag: "Funny"
  },
  {quote: "And Potter, take Weasley with you, he looks far too happy over there",
    source: "McGonagall",
    citation: "Harry Potter and the Half-Blood Prince",
    year: 2005,
    tag: "Funny"
  },
  {quote: "I don't think you're a waste of space... You saved my life.",
    source: "Dudley Dursley",
    citation: "Harry Potter and the Deathly Hallows",
    year: 2007,
    tag: "Love"
  },
  {quote: "Thank you so much Dobby for rescuing me from that cellar. It’s so unfair that you had to die when you were so good and brave. I’ll always remember what you did for us. I hope you’re happy now.",
    source: "Luna Lovegood",
    citation: "Harry Potter and the Deathly Hallows",
    year: 2007,
    tag: "Love"
  },
  {quote: "I don't know how to break this to you...but I think they might have noticed we broke into Gringotts.",
    source: "Ron Weasley",
    citation: "Harry Potter and the Deathly Hallows",
    year: 2007,
    tag: "Funny"
  },
  {quote: "Secrets and lies, that's how we grew up, and Albus ... he was a natural.",
    source: "Aberforth Dumbledore",
    citation: "Harry Potter and the Deathly Hallows",
    year: 2007,
    tag: "Truth"
  },
  {quote: "The thing is, it helps when people stand up to them, it gives everyone hope. I used to notice that when you did it, Harry.",
    source: "Neville Longbottom",
    citation: "Harry Potter and the Deathly Hallows",
    year: 2007,
    tag: "Inspiration"
  },
  {quote: "If he could only have understood the precise and terrible power of that sacrifice, he would not, perhaps, have dared to touch your blood... But then, if he had been able to understand, he could not be Lord Voldemort, and might never have murdered at all.",
    source: "Dumbledore",
    citation: "Harry Potter and the Deathly Hallows",
    year: 2007,
    tag: "Hate"
  },
  {quote: "Do not pity the dead, Harry. Pity the living, and, above all those who live without love.",
    source: "Dumbledore",
    citation: "Harry Potter and the Deathly Hallows",
    year: 2007,
    tag: "Love"
  },
  {quote: "NOT MY DAUGHTER, YOU BITCH!",
    source: "Molly Weasley",
    citation: "Harry Potter and the Deathly Hallows",
    year: 2007,
    tag: "Love"
  },
  {quote: "That wand's more trouble than it's worth. And quite honestly, I've had enough trouble for a life time.",
    source: "Harry Potter",
    citation: "Harry Potter and the Deathly Hallows",
    year: 2007,
    tag: "Truth"
  }
];
